### PR TITLE
Include intermediate certificates in certificate chain

### PR DESCRIPTION
**Pull request by joshtriplett**
When loading a certificate into a CertifiedKey, whether newly signed or
previously saved, load any intermediate certificates as well.

Many HTTPS clients will not accept the certificate chain without the
intermediate certificates included.

### CODE REVIEW

**Comment by joshtriplett** [comment]
I ran into this when trying to run an API server using `rustls-acme`. Some browsers leniently accept certificates without a certificate chain included, but other TLS clients do not.

**Comment by FlorianUekermann** [comment]
Thanks. Looks good to me at first glance. I suspected something like this may be necessary. I'll do a little testing and tag new release soon.

I wonder if the user may want to have control over this to reduce the connection overhead. I won't introduce config options until the need is more obvious, but I have seen environments where the bandwidth consumed by TLS certificates came at a significant cost.

**Comment by joshtriplett** [comment]
I can certainly imagine scenarios at scale where it may make sense to do that kind of optimization at the expense of some clients, such as when you control both ends of the connection. I definitely think that level of configurability would need some careful consideration and documentation.

**Comment by FlorianUekermann** [comment]
Looking back on the setup where cert sizes were an issue, we did have control of both ends and also signed or pinned our own certificates there. So this crate wouldn't have been useful anyway.

**Comment by joshtriplett** [comment]
Thank you for the update and release!

**Pull request merged**
